config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  #restFull routing

  resources :locations do
  	collection do
  		post :save_shared_location
  		get :share_location
  	end
  end

  resources :users do
  	collection do
  		get :get_all_latlong_details
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :shared_locations
	 validates :longitude, :presence => true
	 validates :longitude, :presence => true
end

app/models/shared_location.rb
class SharedLocation < ApplicationRecord
	belongs_to :user
	belongs_to :location
	validates :user_id,:presence=>true
	validates :location_id,:presence=>true
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shared_locations
  validates :email, :uniqueness => true
  validates :username, :uniqueness => true


  def self.get_all_users(user)
  	(user.present?) ? self.where("id != (?)",user.id) : []
  end

	def get_public_locations(all=nil)
		shared_locations = (all==true) ? self.shared_locations : self.shared_locations.where(:is_public=>true) #if self.shared_locations
    (shared_locations and shared_locations.present?) ? Location.where(:id => shared_locations.collect(&:location_id)) : []
	end

  def get_location_shared_with_current_user
    shared_locations = SharedLocation.where(:target_user=>self.id)
    (shared_locations and shared_locations.present?) ? Location.where(:id => shared_locations.collect(&:location_id)) : []
  end

  def fullname
    fname = ""
    fname += self.firstname.capitalize if self.firstname
    fname += " "+self.lastname.capitalize if self.lastname
    fname
  end

  def self.find_for_database_authentication(conditions={})
  find_by(username: conditions[:email]) || find_by(email: conditions[:email])
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_action :authenticate_user!


	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :firstname, :lastname, :password, :password_confirmation])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :password])
	end

	def after_sign_in_path_for(resource)
    	stored_location_for(resource) || landing_upon_sign_in
  	end

  	def landing_upon_sign_in
    	"/"
  	end


  	private
	def after_sign_out_path_for(resource)
		stored_location_for(:user) || root_path
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@page_title = "Home"
		@user = current_user
		@all_users = User.get_all_users @user
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController


	def share_location
		@page_title = "Share Location"
		@all_users = User.get_all_users current_user
	end

	def save_shared_location
		flag = false
		if params[:latitude] != "" and params[:longitude] != ""
			location = Location.create!(:latitude=>params[:latitude], :longitude=>params[:longitude])
			if params[:is_public] and params[:is_public]=="true"
				shared_loc = SharedLocation.new
				shared_loc.user_id = current_user.id
				shared_loc.location_id = location.id
				shared_loc.is_public =  true
				flag = shared_loc.save ? true : false
			else
				user_ids = params[:users].split(",")
				user_ids.map{|u|
					share_location = SharedLocation.new
					share_location.location_id = location.id
					share_location.user_id = current_user.id
					share_location.target_user = u
					flag = share_location.save ? true : false
				}
			end
		else
			message = "Please select a location"
		end
		message = (flag==true) ? "Data saved succesfully" : "Something went wrong"

   		respond_to do |format|
          format.json {render :json => {"flag"=>flag,"message"=>message}}
      	end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user,:only => [:show]
	
	def get_all_latlong_details
		all_public_shared_locations = (params[:username] and params[:username].present?) ? User.find_by_username(params[:username]).get_public_locations : current_user.get_public_locations(true)
		all_location_shared_with_current_user = current_user.get_location_shared_with_current_user

		all_public_shared_locations_hash = Hash.new
		all_location_shared_with_current_user_hash = Hash.new


		all_public_shared_locations.each_with_index{ |location,index| all_public_shared_locations_hash["public_location_#{index+1}"] = {
			"lon" => location.longitude,
			"lat" => location.latitude
			}
    	}
    	all_location_shared_with_current_user.each_with_index{ |location,index| all_location_shared_with_current_user_hash["location_been_shared_#{index+1}"] = {
			"lon" => location.longitude,
			"lat" => location.latitude
			}
    	}

    	data = {
    		"public_shared_locations" => all_public_shared_locations_hash,
    		"location_shared_with_user" => all_location_shared_with_current_user_hash
    	}

        respond_to do |format|
          format.json{render :json=>data}
        end
	end

	def show
		@page_title = "User Page"
	end

	private

	def find_user
		@user = User.find_by_username(params[:id]) or raise(ActiveRecord::RecordNotFound) if params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_welcome_message(user)
		if action_name=="index" 
			"Welcome <strong>#{user.fullname}</strong> to Location Sharing App".html_safe
		elsif action_name=="show"
			"Location shared by <strong>#{user.fullname}</strong>".html_safe
		else
			""
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_map_tab_content.html.erb
<div class=""><br>
    <div class="map" id="map"></div>
</div>

app/views/home/index.html.erb
<div class="container">
  <br>
  <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" data-map="my-shared-places" name="my-places" href="#tab-1">Places</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" name="all-users" href="#tab-2">Users</a>
        </li>
    </ul>

  <!-- Tab panes -->
    <div class="tab-content">
        <div id="tab-1" class="container tab-pane active"><br>
            <div class="map" id="map"></div>
            <div class="row">
              <p><h3>Please note that, <span class="yellow">yellow</span> coloured marker denotes the location(s) shared with you by other users and the <span class="green">green</span> ones are the location shared by you.</h3></p>
            </div>
        </div>
        <div id="tab-2" class="container tab-pane"><br>
          <div>
            <%@all_users.each do |user|%>
              <a href="users/<%=user.username%>" target="_blannk"><h3><%= user.fullname%></h3></a></br>
            <%end%>
          </div>
        </div>

        <%= link_to share_location_locations_path,:target=>"blank" do %>
            <button class="btn btn-success btn md" title="click to share location">Share Location</button>
        <%end%>
    </div>
</div>

app/views/home/user_show.html.erb
<div class="map" id="map"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapProject<%=(@page_title and @page_title.present?) ? " - #{@page_title}" : ""%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'map' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css">

    <!-- bootstrap4 -->
 
  </head>
  <body>
    <% if !current_user.nil? %>
        <header class="row bg-purple">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-sm bg-light text-right">
                    <%= link_to destroy_user_session_path, method: :delete do %><h2>Log out</h2><% end %>
                </nav>
            </div>
        </header>
    <%end%>
    <% if current_user.nil? %>
        <%if action_name != "new"%>
            <%= link_to new_user_session_path, class: 'login-button' do %>Sign in<% end %>
        <%end%>
    <% else %>
        <h2>
            <%= get_welcome_message(@user) %>
        </h2>
    <%end%>
    <!-- <p class = "notice" ><%#= notice %> </p>
    <p class = "alert" ><%#= alert %></p> -->
    <%= yield %>
    <%= javascript_pack_tag 'map' %>
    <div id=pagetitle type="hidden" title="<%=@page_title%>" username="<%=(params[:id] and params[:id].present? ? params[:id] : "")%>"=></div>
  </body>

</html>

app/views/locations/share_location.html.erb
<div id="map" class="map"></div>

<h2>Latitude: <span id="lat"></span> </h2>
<h2>Longitude: <span id="lon"></span></h2>
<button class="btn btn-md btn-warning btnShareOptions" >share options</button>
<div class="row publicDiv">
	<div  class="col-6">
		<div class="col-6">
			<div class="custom-control custom-radio custom-control-inline ">
				<input type="radio" class="custom-control-input" id="public-radio-btn" name="example" value="public">
				<label class="custom-control-label" for="public-radio-btn">Public</label>
			</div>
		</div>
	</div>
</div>
<div class="col-6 friendsDiV">
	<div class="custom-control custom-radio custom-control-inline btnFriends">
		<input type="radio" class="custom-control-input" id="friends-radio-btn" name="example" value="friends">
		<label class="custom-control-label" for="friends-radio-btn">Friends</label>
	</div>
</div>
<div class="col-12 frndShareOptions">

	<div class="description">share with selected user</div></br>

	<%@all_users.each_with_index do |user,index|%>
		<div class="col-6">
			<div class="custom-control custom-checkbox">
				<input type="checkbox" class="custom-control-input user-checkbox" id="radio-<%=index%>" name="users" value="<%=user.id%>">
				<label class="custom-control-label" for="radio-<%=index%>"> <%=user.username%></label>
			</div>
		</div>
	<%end%>
</div>
<button class="btn btn-sm btn-success btnfinalShare" style="width: 114px;">Share Now</button>

</div>

app/views/users/show.html.erb
<div class="map" id="map"></div>